### PR TITLE
fix: preserve scale type in selected attribute, fixes #1224

### LINKED ISSUE #1224: BrushIntervalSelector returns numpy.float32 for DateScale axis instead of numpy.datetime64
Prior to release 0.12.18, the BrushIntervalSelector returned a 'numpy.datetime64' object for a Figure created with a DateScale axis.
After the release, it now returns a 'numpy.float32' object.

It may be related to [PR1202](https://github.com/bqplot/bqplot/pull/1202).

Sample code (sorry for the less than minimal example):

```
import numpy as np
import pandas as pd

from bqplot import *
from bqplot.interacts import BrushIntervalSelector


class LinePlot:
    def __init__(self, x_data, y_data):
        self.x_data = x_data 
        self.y_data = y_data
        # scales
        self.xs = DateScale()
        self.ys = LinearScale()

        # mark or figure type
        self.line = Lines(x=self.x_data, y=self.y_data, scales={'x': self.xs, 'y': self.ys})

        self.xax = Axis(scale=self.xs, label='Time', grids='on', tick_format='%H:%M:%S', tick_rotate=30)
        self.yax = Axis(scale=self.ys, orientation='vertical', grids='on', grid_lines='dashed')

        self.fig = Figure(marks=[self.line], axes=[self.xax, self.yax])
########

class LinePlotBrush(LinePlot):
    def __init__(self, x_data, y_data):
        super().__init__(x_data, y_data)
    
        self.brushintsel = BrushIntervalSelector(scale=self.xs)

        self.fig = Figure(marks=[self.line], axes=[self.xax, self.yax], interaction=self.brushintsel)
########

# creating fake data just to test
rng = pd.date_range('27/10/2018 13:00:00', periods=5000, freq='50ms')
raw_data = pd.DataFrame(data=rng, columns=['Time'])
raw_data.set_index(['Time'], inplace=True)
raw_data['counter'] = np.arange(len(raw_data))

current_plot_data = raw_data
slice_plot = LinePlotBrush(current_plot_data.index.values, current_plot_data['counter'])
slice_plot.fig
```

Desired output (as **BEFORE** 0.12.18):
`print(slice_plot.brushintsel.selected[0])
print(type(slice_plot.brushintsel.selected[0]))`

2018-10-27T13:01:12.630
<class 'numpy.datetime64'>

Output **AFTER** 0.12.18:
`print(slice_plot.brushintsel.selected[0])
print(type(slice_plot.brushintsel.selected[0]))`

1540645300000.0
<class 'numpy.float32'>

### PR DESCRIPTION
**Pull request by maartenbreddels**
Fix #1224

Example:
```python
from bqplot import *
from ipywidgets import *
from bqplot.interacts import *

scale_x1 = DateScale()
scale_y1 = OrdinalScale()
x = np.arange('2020-01-01', '2020-04-01', dtype='datetime64[M]')
scatter1 = Scatter(x=x, y=[3,2,1], scales={'x':scale_x1, 'y':scale_y1})
fig1 = Figure(marks=[scatter1], interaction=BrushSelector(x_scale=scale_x1,
                     y_scale=scale_y1, marks=[scatter1]), background_style={'fill':'#eee'})

fig1
```
image

### CODE REVIEW

File: js/src/OrdinalScaleModel.ts [hunk 1]
```diff
@@ -26,6 +26,10 @@ export class OrdinalScaleModel extends ScaleModel {
         };
     }
 
+    typed(values) {
+        return new Int32Array(values.map(Number));
```
Comment (martinRenou) [inline js/src/OrdinalScaleModel.ts:30]: Is it true that it's an Int32Array?

Couldn't the array be something like `['A', 'B', 'C', 'D']`

Comment (maartenbreddels) [reply js/src/OrdinalScaleModel.ts:30]: Ok, we're talking about the domain here, which in the case of ordinal is integer, maybe rename it to `typedRange(values)` ?

Comment (maartenbreddels) [reply js/src/OrdinalScaleModel.ts:30]: (typo, domain->range)
